replacements:
  bbq: barbeque
  bar-b-q: barbeque
  bar b q: barbeque
  stirfry: stir fried
  stir-fry: stir fried
  veg: vegetables
  veggy: vegetables
  veggies: vegetables
  flax: flax seed
  hemp: hempseed
  chia: chia seeds
  skyr: skyr yogurt
  grn: green
  yog: yogurt
  parm: parmesan
  mozz: mozzarella
  chedd: cheddar
  avo: avocado
  pb: peanut butter
  mayo: mayonnaise
  chkn: chicken
  gnd beef: ground beef
  choysum: choy sum
  choi sum: choy sum
  bokchoi: bok choy
  bk choy: bok choy
  gailan: gai lan
  kai lan: gai lan
  napa: napa cabbage
  rice nood: rice noodles
  jook: congee
  wood fungus: wood ear mushroom
  black fungus: wood ear mushroom
  wood ear: wood ear mushroom
  wonton wrap: wonton wrapper
  wonton wraps: wonton wrapper
  spring rolls: spring roll
  egg rolls: egg roll
  shitake: shiitake mushroom
